#!/usr/bin/env ruby

require "curses"
require_relative "lib/console"
require_relative "lib/menu"
require_relative "lib/player"
require_relative "lib/game_object"
require_relative "lib/scene"

Curses.raw
Curses.noecho
Curses.init_screen
Curses.stdscr.keypad(true)
Curses.curs_set(0)
Curses.refresh

# init
Console.start(22, 5)
scene = Scene.new
scene.set_player(Player.new, 1, 1)

scene.add_object(Pizza.new, 3, 3)

inventory_menu = InventoryMenu.new(30, 20, scene.width, scene.height)
help_menu = HelpMenu.new(30, 10, scene.width, scene.height)

loop do
	scene.draw
	Console.draw

	key = Curses.getch

	case key
	when 258
		scene.move_player(:down)
	when 259
		scene.move_player(:up)
	when 260
		scene.move_player(:left)
	when 261
		scene.move_player(:right)
	when "i"
		inventory_menu.draw(scene.player.inventory)
		Curses.getch
		inventory_menu.hide
	when "p"
		scene.pickup_item
	when "q"
		scene.close
		Console.close
		inventory_menu.close
		help_menu.close
		Curses.close_screen
		exit
	when "?"
		help_menu.draw
		Curses.getch
		help_menu.hide
	else
		Console.log(key.inspect, true)
	end
end
